# 
FROM python:3.9-slim

EXPOSE $PORT

WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./app /code/app

# 
CMD exec uvicorn app.main:app --port $PORT --host 0.0.0.0
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", $PORT]
